### ISSUE TITLE
Get access to CERN's REANA instance and run first example

### ISSUE THREAD

**Issue by matthewfeickert** [Samcoodess/reana-dms#3]
* [x] Go to https://reana.cern.ch/ and login with your CERN Single Sign On credentials
* [x] From your profile (https://reana.cern.ch/profile) record your `REANA_ACCESS_TOKEN` in a secure manner (recommendation: a password manager application)
   - You'll need your `REANA_SERVER_URL` as well, but that's public information (`https://reana.cern.ch`) that doesn't need to be protected
* [x] Create a new Python virtual environment for testing REANA
* [x] Run through the ["first example" in the REANA "Getting started" docs](https://docs.reana.io/getting-started/first-example/) using that Python virtual environment

(This Issue is unrelated to Issue #1 and is just to get used to working with REANA. Once we reach a point where we can understand how to turn https://github.com/Cisneros-Galaxy/RCFM into something we can implement in a workflow language then we can use a similar workflow to the one you learn here to implement the analysis on REANA.)

**Comment by Samcoodess** [comment]
#4
